version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8-jessie
    steps:
      - checkout
      - run:
          name: apt-get
          command: sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: python and pip version
          command: python3 --version
          pip3 --version
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run: 
          name: Packer Download
          command: wget -q https://releases.hashicorp.com/packer/0.9.0/packer_0.9.0_linux_386.zip
          unzip packer_0.9.0_linux_386.zip
          ls -al
          chmod +x packer
          ls -al
      - run:
          name: Validate & Build AMI
          command: ./packer validate -var-file=ami-vars-local.json centos-ami.json 
                  ./packer build -var-file=ami-vars-local.json centos-ami.json